name: Build Release
on:
  push:
    tags:
      - 'v*' # Сработает, когда вы создадите тег версии (например, v1.0)

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build EXE
        run: pyinstaller --onefile main.py # Замените main.py на ваш главный файл

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}